GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/24

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "subscribedToChannel": "beazybee"
}
